### ISSUE TITLE
[Incompatbility] Weather2 rain doesn't extinguish campfires

### ISSUE THREAD

**Issue by guivnf** [restonic4/Rain-should-extinguish-campfires#1]
So this mod called Wheather, Storms & Tornados, formerly called Weather2 changes the rain & weather of minecraft to be more complex and more interesting, but in the process they also override the vanilla rain methods with their own, so i'm here to request a fix for this incompatbility between this mod and [Weather2](https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes)

Their source code: https://github.com/Corosauce/weather2

**Comment by guivnf** [comment]
Fixed it by enabling overcastMode = true (On Weather2 Config)

**Comment by restonic4** [comment]
Oh, thanks for telling me about the issue ^^
